//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Soporte.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libreria.Soporte.Recursos.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Libreria].[ActualizarAutores].
        /// </summary>
        public static string SPActualizarAutores {
            get {
                return ResourceManager.GetString("SPActualizarAutores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Libreria].[ActualizarLibros].
        /// </summary>
        public static string SPActualizarLibros {
            get {
                return ResourceManager.GetString("SPActualizarLibros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Libreria].[ConsultarAutoresById].
        /// </summary>
        public static string SPConsultarAutorById {
            get {
                return ResourceManager.GetString("SPConsultarAutorById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Libreria].[ConsultarAutores].
        /// </summary>
        public static string SPConsultarAutores {
            get {
                return ResourceManager.GetString("SPConsultarAutores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Libreria].[ConsultarCiudades].
        /// </summary>
        public static string SPConsultarCiudades {
            get {
                return ResourceManager.GetString("SPConsultarCiudades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Libreria].[ConsultarDepartamentos].
        /// </summary>
        public static string SPConsultarDepartamento {
            get {
                return ResourceManager.GetString("SPConsultarDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Libreria].[ConsultarLibrosById].
        /// </summary>
        public static string SPConsultarLibroById {
            get {
                return ResourceManager.GetString("SPConsultarLibroById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Libreria].[ConsultarLibros].
        /// </summary>
        public static string SPConsultarLibros {
            get {
                return ResourceManager.GetString("SPConsultarLibros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Libreria].[ConsultarPaises].
        /// </summary>
        public static string SPConsultarPais {
            get {
                return ResourceManager.GetString("SPConsultarPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Libreria].[ConsultarSexos].
        /// </summary>
        public static string SPConsultarSexo {
            get {
                return ResourceManager.GetString("SPConsultarSexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Libreria].[EliminarAutor].
        /// </summary>
        public static string SPEliminarAutor {
            get {
                return ResourceManager.GetString("SPEliminarAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Libreria].[EliminarLibro].
        /// </summary>
        public static string SPEliminarLibro {
            get {
                return ResourceManager.GetString("SPEliminarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Libreria].[InsertarAutores].
        /// </summary>
        public static string SPInsertarAutores {
            get {
                return ResourceManager.GetString("SPInsertarAutores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Libreria].[InsertarLibros].
        /// </summary>
        public static string SPInsertarLibros {
            get {
                return ResourceManager.GetString("SPInsertarLibros", resourceCulture);
            }
        }
    }
}
